const books: Book[] = [
  {
    id: '1',
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    description: 'Timeless principles of wealth creation, personal achievement, and mindset mastery.',
    filename: 'think-and-grow-rich-by-napolean-hill.pdf',
    category: 'Wealth & Mindset',
  },
  {
    id: '2',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    description: 'Exploration of the two systems that drive the way we think, judge, and make choices.',
    filename: 'thinking-fast-and-slow-by-Daniel-Kahneman.pdf',
    category: 'Psychology',
  },
  {
    id: '3',
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen Covey',
    description: 'Powerful lessons in personal change, character ethics, and principled effectiveness.',
    filename: 'covey-stephen-the-seven-habits-of-highly-effective-people-by-Stephen-Covey.pdf',
    category: 'Leadership',
  },
  {
    id: '4',
    title: 'How to Win Friends and Influence People',
    author: 'Dale Carnegie',
    description: 'Classic guide on interpersonal communication, persuasion, and building lasting relationships.',
    filename: 'How-to-win-friends-and-influence-people-by-Dale-carnegie.pdf',
    category: 'Communication',
  },
  {
    id: '5',
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'An easy and proven way to build good habits, break bad ones, and get 1% better every day.',
    filename: 'Atomic-Habits-by-James-Clear.pdf',
    category: 'Productivity',
  },
]; 